# Mapping to 5 entity types present in all domains
# (person, location, organisation, misc, event)

entity_to_generic = {
    "academicjournal": "misc",
    "album": "misc",
    "algorithm": "misc",
    "astronomicalobject": "misc",
    "award": "misc",
    "band": "organisation",
    "book": "misc",
    "chemicalcompound": "misc",
    "chemicalelement": "misc",
    "conference": "event",
    "country": "location",
    "discipline": "misc",
    "election": "event",
    "enzyme": "misc",
    "event": "event",
    "field": "misc",
    "literarygenre": "misc",
    "location": "location",
    "magazine": "misc",
    "metrics": "misc",
    "misc": "misc",
    "musicgenre": "misc",
    "musicalartist": "person",
    "musicalinstrument": "misc",
    "organisation": "organisation",
    "person": "person",
    "poem": "misc",
    "politicalparty": "organisation",
    "politician": "person",
    "product": "misc",
    "programlang": "misc",
    "protein": "misc",
    "researcher": "person",
    "scientist": "person",
    "song": "misc",
    "task": "misc",
    "theory": "misc",
    "university": "organisation",
    "writer": "person",
}
